apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-api
  name: my-api
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - image: denilbhatt0814/test-webapp:latest
          name: my-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
